# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Andrew Grabko
email: andrew.grabko@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ttrevan.github.io" # the base hostname & protocol for your site

# accounts
twitter_username: t_revan
github_username:  ttRevan

# Build settings
markdown: kramdown
